# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created: Thu Oct 15 23:56:19 2009
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_qUimge_main(object):
    def setupUi(self, qUimge_main):
        qUimge_main.setObjectName("qUimge_main")
        qUimge_main.resize(503, 549)
        self.centralwidget = QtGui.QWidget(qUimge_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(481, 451))
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.UploadTab = QtGui.QWidget()
        self.UploadTab.setObjectName("UploadTab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.UploadTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SelectHost = QtGui.QComboBox(self.UploadTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SelectHost.sizePolicy().hasHeightForWidth())
        self.SelectHost.setSizePolicy(sizePolicy)
        self.SelectHost.setMaxVisibleItems(30)
        self.SelectHost.setIconSize(QtCore.QSize(23, 23))
        self.SelectHost.setObjectName("SelectHost")
        self.horizontalLayout.addWidget(self.SelectHost)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.DeleteSelected = QtGui.QPushButton(self.UploadTab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/app/gtk-close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DeleteSelected.setIcon(icon)
        self.DeleteSelected.setCheckable(False)
        self.DeleteSelected.setObjectName("DeleteSelected")
        self.horizontalLayout.addWidget(self.DeleteSelected)
        self.ClearUploadList = QtGui.QPushButton(self.UploadTab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/app/edit-clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ClearUploadList.setIcon(icon1)
        self.ClearUploadList.setObjectName("ClearUploadList")
        self.horizontalLayout.addWidget(self.ClearUploadList)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalWidget = QtGui.QWidget(self.UploadTab)
        self.horizontalWidget.setEnabled(True)
        self.horizontalWidget.setAutoFillBackground(False)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.progressBar = QtGui.QProgressBar(self.horizontalWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.verticalLayout_2.addWidget(self.horizontalWidget)
        self.UploadList = QtGui.QListWidget(self.UploadTab)
        self.UploadList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.UploadList.setIconSize(QtCore.QSize(100, 100))
        self.UploadList.setMovement(QtGui.QListView.Static)
        self.UploadList.setProperty("isWrapping", True)
        self.UploadList.setResizeMode(QtGui.QListView.Adjust)
        self.UploadList.setLayoutMode(QtGui.QListView.Batched)
        self.UploadList.setSpacing(5)
        self.UploadList.setViewMode(QtGui.QListView.IconMode)
        self.UploadList.setUniformItemSizes(True)
        self.UploadList.setBatchSize(1003)
        self.UploadList.setObjectName("UploadList")
        self.verticalLayout_2.addWidget(self.UploadList)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/app/gtk-go-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.UploadTab, icon2, "")
        self.ResultTab = QtGui.QWidget()
        self.ResultTab.setObjectName("ResultTab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.ResultTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ModePrint = QtGui.QComboBox(self.ResultTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ModePrint.sizePolicy().hasHeightForWidth())
        self.ModePrint.setSizePolicy(sizePolicy)
        self.ModePrint.setEditable(True)
        self.ModePrint.setFrame(True)
        self.ModePrint.setObjectName("ModePrint")
        self.horizontalLayout_3.addWidget(self.ModePrint)
        self.Delimiter = QtGui.QComboBox(self.ResultTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Delimiter.sizePolicy().hasHeightForWidth())
        self.Delimiter.setSizePolicy(sizePolicy)
        self.Delimiter.setEditable(True)
        self.Delimiter.setObjectName("Delimiter")
        self.horizontalLayout_3.addWidget(self.Delimiter)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.ResultText = QtGui.QTextEdit(self.ResultTab)
        self.ResultText.setReadOnly(False)
        self.ResultText.setObjectName("ResultText")
        self.verticalLayout_3.addWidget(self.ResultText)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/app/format-justify-fill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.ResultTab, icon3, "")
        self.SettingsTab = QtGui.QWidget()
        self.SettingsTab.setObjectName("SettingsTab")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/app/gnome-settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.SettingsTab, icon4, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        qUimge_main.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(qUimge_main)
        self.statusBar.setObjectName("statusBar")
        qUimge_main.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(qUimge_main)
        self.toolBar.setCursor(QtCore.Qt.ArrowCursor)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        qUimge_main.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtGui.QMenuBar(qUimge_main)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 503, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        qUimge_main.setMenuBar(self.menuBar)
        self.action_Open = QtGui.QAction(qUimge_main)
        self.action_Open.setCheckable(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/app/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open.setIcon(icon5)
        self.action_Open.setObjectName("action_Open")
        self.actionUpload = QtGui.QAction(qUimge_main)
        self.actionUpload.setIcon(icon2)
        self.actionUpload.setObjectName("actionUpload")
        self.actionClipboard = QtGui.QAction(qUimge_main)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/app/editcopy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClipboard.setIcon(icon6)
        self.actionClipboard.setObjectName("actionClipboard")
        self.actionExit = QtGui.QAction(qUimge_main)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/app/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon7)
        self.actionExit.setObjectName("actionExit")
        self.actionExit_2 = QtGui.QAction(qUimge_main)
        self.actionExit_2.setObjectName("actionExit_2")
        self.toolBar.addAction(self.action_Open)
        self.toolBar.addAction(self.actionUpload)
        self.toolBar.addAction(self.actionClipboard)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)
        self.menuFile.addAction(self.actionExit_2)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(qUimge_main)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("activated()"), qUimge_main.close)
        QtCore.QObject.connect(self.ClearUploadList, QtCore.SIGNAL("clicked()"), self.UploadList.clear)
        QtCore.QObject.connect(self.actionExit_2, QtCore.SIGNAL("activated()"), qUimge_main.close)
        QtCore.QMetaObject.connectSlotsByName(qUimge_main)
        qUimge_main.setTabOrder(self.tabWidget, self.SelectHost)
        qUimge_main.setTabOrder(self.SelectHost, self.UploadList)
        qUimge_main.setTabOrder(self.UploadList, self.DeleteSelected)
        qUimge_main.setTabOrder(self.DeleteSelected, self.ClearUploadList)
        qUimge_main.setTabOrder(self.ClearUploadList, self.ModePrint)
        qUimge_main.setTabOrder(self.ModePrint, self.Delimiter)

    def retranslateUi(self, qUimge_main):
        qUimge_main.setWindowTitle(QtGui.QApplication.translate("qUimge_main", "quimge", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.UploadTab), QtGui.QApplication.translate("qUimge_main", "Upload list", None, QtGui.QApplication.UnicodeUTF8))
        self.ResultText.setHtml(QtGui.QApplication.translate("qUimge_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ResultTab), QtGui.QApplication.translate("qUimge_main", "Result", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SettingsTab), QtGui.QApplication.translate("qUimge_main", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("qUimge_main", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("qUimge_main", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setText(QtGui.QApplication.translate("qUimge_main", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpload.setText(QtGui.QApplication.translate("qUimge_main", "&Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpload.setToolTip(QtGui.QApplication.translate("qUimge_main", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClipboard.setText(QtGui.QApplication.translate("qUimge_main", "&Clipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClipboard.setToolTip(QtGui.QApplication.translate("qUimge_main", "Copy to clipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("qUimge_main", "&Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit_2.setText(QtGui.QApplication.translate("qUimge_main", "&Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit_2.setToolTip(QtGui.QApplication.translate("qUimge_main", "Exit", None, QtGui.QApplication.UnicodeUTF8))

